# Generated by Django 5.0.7 on 2024-07-16 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('genre', models.CharField(max_length=100)),
                ('members', models.CharField(max_length=500)),
                ('years_active', models.CharField(max_length=50)),
                ('band_description', models.TextField(max_length=700)),
                ('image_url', models.URLField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='no name', max_length=200)),
                ('date', models.DateField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('description', models.TextField(default='no description', max_length=700)),
                ('ticket_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_popular', models.BooleanField(default=False)),
                ('image_url', models.URLField(max_length=500, null=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='tickit.artist')),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='no name', max_length=200)),
                ('address', models.TextField(default='no address', max_length=400)),
                ('parking', models.BooleanField(default=False)),
                ('parking_specifics', models.TextField(default='no parking', max_length=500)),
                ('date', models.DateField(blank=True, null=True)),
                ('contact_email', models.CharField(default='no email', max_length=200)),
                ('contact_phone', models.CharField(default='no phone', max_length=200)),
                ('capacity', models.IntegerField(default='no default')),
                ('accessible_seating', models.BooleanField(default=False)),
                ('image_url', models.URLField(default='no image', max_length=600)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venues', to='tickit.event')),
            ],
        ),
    ]
