# Generated by Django 5.0.7 on 2024-07-15 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='no name', max_length=200)),
                ('date', models.DateField(default='no date')),
                ('time', models.TimeField(default='no time')),
                ('description', models.TextField(default='no description', max_length=700)),
                ('ticket_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image_url', models.URLField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField(max_length=400)),
                ('parking', models.BooleanField(default=False)),
                ('parking_specifics', models.TextField(max_length=500)),
                ('contact_email', models.CharField(max_length=200)),
                ('contact_phone', models.CharField(max_length=200)),
                ('capacity', models.IntegerField()),
                ('accessible_seating', models.BooleanField(default=False)),
                ('image_url', models.URLField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='no name', max_length=200)),
                ('genre', models.CharField(default='no genre', max_length=100)),
                ('members', models.CharField(default='no members', max_length=500)),
                ('years_active', models.CharField(default='no years', max_length=50)),
                ('band_description', models.TextField(default='no description', max_length=700)),
                ('image_url', models.URLField(max_length=500, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artists', to='tickit.event')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='tickit.venue'),
        ),
    ]
