# Generated by Django 5.0.7 on 2024-07-18 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickit', '0002_remove_venue_date_remove_venue_event_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='artist',
            table='artists',
        ),
        migrations.AlterModelTable(
            name='event',
            table='events',
        ),
        migrations.AlterModelTable(
            name='eventvenue',
            table='event_venues',
        ),
        migrations.AlterModelTable(
            name='venue',
            table='venues',
        ),
    ]
